Set the Windows Terminal as the default terminal
mandiant/VM-Packages pull request #1093
Opened 2024-06-14 11:37 UTC by d35ha

Closes https://github.com/mandiant/VM-Packages/issues/971.

2024-06-14 15:35 UTC, Ana06 commented
I am not sure this works as proposed in #971. @d35ha can you provide more details or how this works and how it looks like (maybe adding a screenshot)?

2024-06-14 15:46 UTC, d35ha commented
@Ana06 
I've created a console app, here is it how its execution looks before and after setting these registry values:

![before](https://github.com/mandiant/VM-Packages/assets/43878201/6029e92d-c071-4ee8-9afa-16bf44e278c7)

![after](https://github.com/mandiant/VM-Packages/assets/43878201/9ee0e62f-7b9c-4ee0-9fa0-21666e2c52a9)

Also, running `cmd` or `powershell` opens it in Windows Terminal.

2024-06-18 10:41 UTC, Ana06 commented
@d35ha is proposing using the windows terminal to open the shortcuts in the Tools directory, is this PR achieving this?

2024-06-24 05:47 UTC, d35ha commented
@Ana06 
Any application that requires a console would be assigned the Windows terminal console instead of the the old conhost.exe (that is including the shortcuts under the Tools directory).

2024-07-01 08:32 UTC, Ana06 requested changes

2024-07-01 08:32 UTC, Ana06 commented on packages/windows-terminal.vm/tools/chocolateyinstall.ps1
> +  # Set windows terminal as the default terminal (effective only when OS Build >= 19045.3031)
I am using `10.0.19045.0` (downloaded from the recommended link in FLARE-VM), so this approach does not work

2024-10-24 18:26 UTC, emtuls commented
I looked into this a little bit more.

I wanted to try and find a way to have any "console app" shortcut open with `Windows Terminal` (if it exists) or `cmd.exe` if not, but the way to make that happen would likely require an external script to launch the correct one. I tried creating a singular command that can be done within a shortcut target cmd, but it ended up being too long.

An alternative would be that we force `Windows Terminal` to be installed, but I believe this would require modification of our install script so that it is always installed if I'm not mistaken?

Let me know if that's the preferred route and I can work on that.

2024-10-24 22:58 UTC, emtuls commented
I got something mostly working for Command Prompt, but it seems like Powershell is going to be a lot more of an issue due to a long standing bug with Windows Terminal and how it interprets semicolons: https://github.com/microsoft/terminal/issues/13264

This makes it very difficult, if not impossible to do our powershell shortcuts. I was able to make one work, but it would require removing the "Write-Host" portion (echoing the command we write into the console).

For reference, I modified `powersploit` to use this as a shortcut target: `"C:\Tools\Windows Terminal\terminal-1.19.10573.0\wt.exe" -p "PowerShell" "powershell.exe -NoExit -Command ""Get-Command -Module (Import-Module .\Recon\Recon.psd1)""`

This still seems to work as expected, just a re-write of the original command we used: `Import-Module .\Recon\Recon.psd1 ; Get-Command -Module Recon`

2024-11-04 15:51 UTC, Ana06 commented
Thanks for the research @emtuls! I suggest we merge this PR as it is, as it seems it is not easy to support it in our Windows version.

2024-11-06 12:11 UTC, Ana06 approved these changes
I think it is nice that previous versions benefit from the improvement even if it does not work in older version. I have tested it in `10.0.19045.0` and it does not seem to introduce any issues (it also does modify the behavior).

2025-08-15 23:06 UTC, emtuls commented
I'm in favor of closing this as I don't think it is feasible to make it work as expected for Windows 10 at this moment.

2025-08-15 23:06 UTC, closed without merging