Use SigCheck w/ Zimmerman Tools
mandiant/VM-Packages pull request #1199
Opened 2024-12-12 06:20 UTC by emtuls

This fixes many of the tools that are running into an error in our Daily checks (https://github.com/mandiant/VM-Packages/wiki/Daily-Failures). These specific tools run into an issue where we need to manually update the hashes due to the links not having a version in them so our updater does not properly update the packages for us.

Specifically, this fixes:
-  `evtxecmd.vm`
-  `pecmd.vm`
-  `recmd.vm`
-  `registry_explorer.vm`
-  `rla.vm`
-  `sqlecmd.vm`

2024-12-12 09:51 UTC, Ana06 requested changes
This is a great improvement, thanks for working on this @emtuls!! :sparkling_heart: 

I do not like that we have a code that is long and complicated repeated in many packages. could you please add a helper function that we can reuse so that the code in every of the packages is simple and the complicated code is in a single place making it easier to maintain and understand? :pray: 

**Question:** Why can't we use `VM-Assert-Signature` for RegCool? It seem you didn't need to do anything special in this case :thinking:

2024-12-13 02:00 UTC, emtuls commented
> This is a great improvement, thanks for working on this @emtuls!! 💖
> 
> I do not like that we have a code that is long and complicated repeated in many packages. could you please add a helper function that we can reuse so that the code in every of the packages is simple and the complicated code is in a single place making it easier to maintain and understand? 🙏
> 
> **Question:** Why can't we use `VM-Assert-Signature` for RegCool? It seem you didn't need to do anything special in this case 🤔

I've modified the `VM-Install-From-Zip` to include a new argument for verifying a signature. I was a bit hesitant at first to do it because it seems to make the code look a little bit ugly, but I think it is generally fine and makes for the other code bits in each package to be much cleaner.

The alternative would have been its own function, but it would mimic the `VM-Install-From-Zip` function in a lot of ways, so I wasn't sure if that would be any better.


As for why we can't use it with `RegCool`. I believe that this is because the cert used to sign that tool is a self signed cert which is not verified via our method that we use to verify signatures, whereas these tools have a standard CA signing authority.

2024-12-18 23:00 UTC, rltpoa commented
@Ana06 I totally agree with the idea of a "better" code. But meanwhile, new users like me are struggling to complete a fresh install of Flare-VM without running into issues. I think it comes down to weighing both sides... what might be more important at the moment: a not-so-pretty code that could be improved later, or new users having a smooth experience? 

Anyway, sorry to interrupt, but I thought perhaps the perspective of a new user could add to the discussion. Thank you both for all this work.

2025-01-10 14:25 UTC, Ana06 requested changes
Question: Can we now use the helper function to simplify the packages that are already using signature verification (sysinternals, googlechrome, metasploit)?

2025-01-10 14:25 UTC, Ana06 commented on packages/pecmd.vm/tools/chocolateyinstall.ps1
> +VM-Install-From-Zip $toolName $category $zipUrl -zipSha256 $zipSha256 -consoleApp $true -innerFolder $false -verifySignature $true
you need to make the hash optional and remove it from the packages using signature verification:
 ```suggestion
VM-Install-From-Zip $toolName $category $zipUrl -consoleApp $true -innerFolder $false -verifySignature $true
```

2025-01-10 14:25 UTC, Ana06 commented on packages/pecmd.vm/pecmd.vm.nuspec
> +      <dependency id="common.vm" version="0.0.0.20241212" />
you also need to ensure signtool is installed in all the packages that use signature verification
```suggestion
      <dependency id="common.vm" version="0.0.0.20241212" />
      <!-- vcbuildtools.vm installs signtool.exe needed by VM-Assert-Signature -->
      <dependency id="vcbuildtools.vm" />
```

2025-02-03 16:28 UTC, Ana06 commented
I am going to take over as it seems @emtuls does not have time :wink:

2025-02-05 09:48 UTC, sara-rn reviewed
I tested the installation of the packages locally and I got the same error for all. I believe the version of the dependency `common.vm` might need to be updated.
`ERROR: A parameter cannot be found that matches parameter name 'verifySignature'.`

2025-02-05 09:48 UTC, sara-rn commented on packages/evtxecmd.vm/evtxecmd.vm.nuspec
> +      <dependency id="common.vm" version="0.0.0.20241212" />
shouldn't be the version of `common.vm` `0.0.0.20250203` to make sure it accepts the `-verifySignature` parameter?

2025-02-05 09:48 UTC, sara-rn commented on packages/pecmd.vm/pecmd.vm.nuspec
> +      <dependency id="common.vm" version="0.0.0.20241212" />
`<dependency id="common.vm" version="0.0.0.20250203" />`

2025-02-05 11:21 UTC, Ana06 commented
@sara-rn it is surely related to that, as if an older version is installed, the new function introduced in this PR is not available. I forgot to update the version when fixing the conflict in the common nuspec. Good catch!

2025-02-05 14:07 UTC, Ana06 commented
Thanks for the review @sara-rn!

2025-02-05 14:07 UTC, merged