vm.common: add -iconLocation param to VM-Install-From-Zip
mandiant/VM-Packages pull request #1202
Opened 2024-12-12 15:38 UTC by fariss

closes #1187

2024-12-12 20:47 UTC, Ana06 reviewed
Thank for sending a PR to add the `iconLocation` parameter to `VM-Install-From-Zip`! :sparkling_heart: 

As documented in [the wiki](https://github.com/mandiant/VM-Packages/wiki/Chocolatey-packages#non-metapackages):
> The version needs to be increased every time you modify an existing package

Otherwise the package can't be pushed to MyGet, GH actions push it when merging the PR. So you need to modify the version in `packages/common.vm/common.vm.nuspec` to be `0.0.0.20241212`. This is also the reason the linter is not happy.

I recommend to also modify the capa-explorer-web.vm package in the same PR that you add the parameter (if you wish in a different commit) as then we can test that the new modification is working. :wink:

2024-12-18 13:28 UTC, fariss commented on packages/capa-explorer-web.vm/tools/chocolateyinstall.ps1
> +VM-Install-From-Zip $toolName $category $zipUrl $zipSha256 -executableName $executableName -iconLocation $iconName  -withoutBinFile -innerFolder $true
@Ana06 please let me know if this works out for you.

2025-01-10 13:36 UTC, Ana06 requested changes

2025-01-10 13:36 UTC, Ana06 commented on packages/capa-explorer-web.vm/tools/chocolateyinstall.ps1
> +VM-Install-From-Zip $toolName $category $zipUrl $zipSha256 -executableName $executableName -iconLocation $iconName  -withoutBinFile -innerFolder $true
There are two issues:
- You need to request in the nuspec of `capa-explorer-web.vm` that the version of `common.vm` is the one you where you have added the new function (or newer). To do this, the dependency has to be requested as `<dependency id="common.vm" version="0.0.0.20241218" />`
- The `iconLocation` expects an absolute path in `VM-Install-Shortcut`. I think it is good to keep it local here, and look for it inside `$toolDir` in the `VM-Install-From-Zip` function, to pass the absolute path to `VM-Install-Shortcut`.

I recommend you to follow the [_Local Testing_ instruction in the Wiki](https://github.com/mandiant/VM-Packages/wiki/Testing#local-testing) to be able to easily test your changes. If you need any issues or questions while setting a local testing setup, please let me know. I am happy to help! :smile:

2025-02-03 08:51 UTC, fariss commented on packages/capa-explorer-web.vm/tools/chocolateyinstall.ps1
> +VM-Install-From-Zip $toolName $category $zipUrl $zipSha256 -executableName $executableName -iconLocation $iconName  -withoutBinFile -innerFolder $true
@Ana06, thanks for the instructions. I don't have local Windows VM, and unfortunately I ran into multiple problems while trying to test the packages installation out in an EC2 instance using [Local Testing instruction in the Wiki](https://github.com/mandiant/VM-Packages/wiki/Testing#local-testing)

![image](https://github.com/user-attachments/assets/63be6bcb-18b4-4e54-bd14-bbad0980e41f)

2025-04-16 10:22 UTC, Ana06 commented
@fariss it seems you don't have time to finish this PR. @sara-rn can take over, so that we can provide the capa explorer an icon in the next days/weeks. Is this ok with you?

2025-04-16 10:32 UTC, fariss commented
@Ana06 Absolutely, and apologies for not being able to test this out. Thank you!

2025-05-08 18:05 UTC, Ana06 requested changes
@sara-rn thanks for finishing this PR! The code LGTM and I have tested locally and it works as expected too. :tada: Can you please squash the commits into a single one with you as author and @fariss as [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) (or the other way around)?

2025-05-09 07:31 UTC, Ana06 approved these changes
Thanks @sara-rn and @fariss! 💐

2025-05-09 07:32 UTC, merged

2025-05-09 08:45 UTC, fariss commented
Awesome, thank you!