daily: update badge success/failure counts
mandiant/VM-Packages pull request #134
Opened 2022-11-30 16:17 UTC by mr-tz

closes #127

2022-12-01 11:20 UTC, mr-tz commented on .github/workflows/daily.yml
> +          git push
may use an Action like https://github.com/marketplace/actions/add-commit instead

2022-12-02 00:27 UTC, MalwareMechanic commented
Hmm, test if failing:

```
Run git config user.email 'vm-packages@mandiant.com'
  git config user.email 'vm-packages@mandiant.com'
  git config user.name 'vm-packages'
  git add README.md
  git commit -m 'Update daily success/failure badges'
  git push
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
[detached HEAD 9[2](https://github.com/mandiant/VM-Packages/actions/runs/3593784136/jobs/6059268642#step:6:2)72d50] Update daily success/failure badges
 1 file changed, [4](https://github.com/mandiant/VM-Packages/actions/runs/3593784136/jobs/6059268642#step:6:4) insertions(+), 4 deletions(-)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 1.
```

@Ana06 ?

2022-12-02 16:06 UTC, Ana06 requested changes
I tagged the commits to make clear there is only two change requests. Do not forget to remove the testing code and to squash the commits before merging.  You need to also remove the protection of the main branch. 😉

2022-12-02 16:06 UTC, Ana06 commented on .github/workflows/daily.yml
> +          (Get-Content README.md) -replace 'pass-(\d{1,})-', "pass-$succ-" -replace 'fail-(\d{1,})-', "fail-$fail-" -replace 'packages-(\d{1,})-', "packages-$total-" | Out-File README.md
[change request] I would add a bit more context to the replacement (the badge url or part of it) to avoid we replace something else by accident

2022-12-02 19:34 UTC, MalwareMechanic approved these changes

2022-12-02 19:35 UTC, merged