Add ollydbg.scyllahide.vm package
mandiant/VM-Packages pull request #228
Opened 2023-02-03 17:16 UTC by TheoKlein

Add ollydbg.scyllahide.vm package to close #164

2023-02-09 08:28 UTC, mr-tz commented
Thank you! Could you update this like @MalwareMechanic did in #227?

2023-02-09 08:56 UTC, TheoKlein commented
Sure, it's much better!

2023-02-09 17:14 UTC, mr-tz requested changes
thanks, just a few minor things I've noticed before we can merge

2023-02-09 17:14 UTC, mr-tz commented on packages/ollydbg.scyllahide.vm/tools/chocolateyinstall.ps1
> +    packageName   = ${Env:ChocolateyPackageName}
```suggestion
        packageName   = ${Env:ChocolateyPackageName}
```

2023-02-09 17:14 UTC, mr-tz commented on packages/ollydbg.scyllahide.vm/tools/chocolateyinstall.ps1
> +        New-Item -ItemType directory $toolDstDir -Force -ea 0
```suggestion
        New-Item -ItemType directory $toolDstDir -Force -ea 0 | Out-Null
```

2023-02-09 17:14 UTC, mr-tz commented on packages/ollydbg.scyllahide.vm/tools/chocolateyinstall.ps1
> +    VM-Remove-PreviousZipPackage ${Env:chocolateyPackageFolder}
@MalwareMechanic should this be removed here as well?

2023-02-10 08:38 UTC, mr-tz approved these changes
great, thank you!

2023-02-10 08:39 UTC, merged