update version and make package more flexible
mandiant/VM-Packages pull request #240
Opened 2023-02-13 14:18 UTC by mr-tz

2023-02-14 16:29 UTC, MalwareMechanic requested changes

2023-02-14 17:50 UTC, mr-tz commented on packages/ghidra.vm/tools/chocolateyinstall.ps1
> +    $versionPath = 'ghidra_' + $env:ChocolateyPackageVersion + '_PUBLIC'
```suggestion
    $versionPath = 'ghidra_' + $env:ChocolateyPackageVersion -replace '\.\d{4}\d{2}\d{2}$' + '_PUBLIC'
```

2023-02-14 17:50 UTC, mr-tz commented on packages/ghidra.vm/tools/chocolateyinstall.ps1
> +    $versionPath = 'ghidra_' + $env:ChocolateyPackageVersion + '_PUBLIC'
good catch!

2023-02-15 09:16 UTC, mr-tz commented on packages/ghidra.vm/tools/chocolateyinstall.ps1
> +    $versionPath = 'ghidra_' + $env:ChocolateyPackageVersion -replace '\.\d{4}\d{2}\d{2}$' + '_PUBLIC'
```suggestion
    # get version as defined in nuspec and remove potential 4th segment `.YYYYMMDD`
    $version = $env:ChocolateyPackageVersion -replace '\.\d{4}\d{2}\d{2}$'
    $versionPath = 'ghidra_' + $version + '_PUBLIC'
```

2023-02-16 02:25 UTC, MalwareMechanic approved these changes
LGTM!

2023-02-16 10:12 UTC, merged