:robot: Add garbageman.vm
mandiant/VM-Packages pull request #349
Opened 2023-05-24 09:55 UTC by vm-packages

Automated PR from https://github.com/mandiant/VM-Packages/issues/343 :rocket:

2023-06-05 08:42 UTC, Ana06 commented on packages/garbageman.vm/garbageman.vm.nuspec
> +    <description>A set of tools designed for .NET heap analysis. These tools offer the following benefits for malware researchers: Ability to extract clear-text; payload (PE Images etc.) from .NET he
I would short this description to:
```suggestion
    <description>A set of tools designed for .NET heap analysis.</description>
```


From [our wiki](https://github.com/mandiant/VM-Packages/wiki/Package-Structure#description):
> The description should be short and not include version specific details or other information that is likely to change in a future version.

2023-06-06 08:49 UTC, Ana06 requested changes
Similarly as with https://github.com/mandiant/VM-Packages/issues/368, we are missing dependencies here.

![Uploading Screenshot 2023-06-06 at 10.49.15.png…]()

2023-08-25 17:31 UTC, emtuls commented
There is an issue with `GarbageMan` in that it will display an error when opening the GUI, due to relative path usage of a file it depends on. 

The tool works properly if you open it directly from its extracted position, which is not ideal, but could work for the meantime if we intend to merge this before a fix is made.

I have opened an issue for the project repo in regards to the error: https://github.com/WithSecureLabs/GarbageMan/issues/5

![image](https://github.com/mandiant/VM-Packages/assets/35854880/3de827ae-574d-488a-be93-f4aaecc81e9f)

2023-08-25 17:32 UTC, emtuls approved these changes

2023-09-27 11:44 UTC, Ana06 reviewed
I think that is a ugly error and that we should figure out a solution before getting this merged. What about using the current directory the path of GarbageMan? We may not be able to use the helper function or we may need to modify the helper function to add this option.

2023-10-21 02:31 UTC, merged