add ghidra
mandiant/VM-Packages pull request #36
Opened 2022-03-16 08:34 UTC by mr-tz

2022-03-18 15:00 UTC, MalwareMechanic requested changes

2022-04-19 15:58 UTC, MalwareMechanic commented on packages/ghidra.vm/tools/chocolateyuninstall.ps1
> +VM-Remove-Tool-Shortcut $toolName $category
After this add in `Uninstall-BinFile -Name $toolName` and it should be gtg after

2022-04-21 15:20 UTC, mr-tz commented on packages/ghidra.vm/tools/chocolateyuninstall.ps1
> +VM-Remove-Tool-Shortcut $toolName $category
```suggestion
VM-Remove-Tool-Shortcut $toolName $category
Uninstall-BinFile -Name $toolName
```

2022-04-25 13:00 UTC, MalwareMechanic approved these changes

2022-05-02 15:34 UTC, merged