:robot: Add dnspyex.vm
mandiant/VM-Packages pull request #70
Opened 2022-09-12 14:34 UTC by vm-packages

Automated PR from https://github.com/mandiant/VM-Packages/issues/66 :rocket:

2022-09-12 14:38 UTC, Ana06 requested changes

2022-09-12 14:38 UTC, Ana06 commented on pkg.json
> +{
This needs to be removed: https://github.com/mandiant/VM-Packages/pull/69/files#r968504190

2022-09-15 09:11 UTC, Ana06 commented
why is this `scripts/utils/__pycache__/create_package_template.cpython-38.pyc` generated @mr-tz ? 😕 

We may want to:
1. ignore `.pyc` files
2. Instead of deleting created files in the action, commit only the package directory with `add-paths`

2022-09-15 09:15 UTC, mr-tz commented
Ugh, yes, let's explicitly add the created files. I'll take a look into it.

2022-09-15 11:21 UTC, Ana06 approved these changes
This finally looks good!!! 🎉

2022-09-15 11:23 UTC, merged