:robot: Add rpcview.vm
mandiant/VM-Packages pull request #705
Opened 2023-10-18 16:22 UTC by vm-packages

Automated PR from https://github.com/mandiant/VM-Packages/issues/691 :rocket:

2023-10-23 04:20 UTC, binjo commented on packages/rpcview.vm/tools/chocolateyinstall.ps1
> +$toolName = 'RpcView'
```ps1
$toolName = 'RpcView64'
$executableName = 'RpcView.exe'
```

2023-10-23 04:22 UTC, binjo commented on packages/rpcview.vm/tools/chocolateyinstall.ps1
> +VM-Install-From-Zip $toolName $category $zipUrl -zipSha256 $zipSha256 -consoleApp $false
As the folder name is different from the executable name, extra params needed.
```ps1
VM-Install-From-Zip $toolName $category $zipUrl -zipSha256 $zipSha256 -consoleApp $false -executableName $executableName
```

2023-10-23 05:02 UTC, binjo commented on packages/rpcview.vm/tools/chocolateyinstall.ps1
> +$toolName = 'RpcView'
`-innerFolder $true` looks better, with the directory structure:
```
Extracting C:\Users\runneradmin\AppData\Local\Temp\chocolatey\rpcview.vm\0.3.1.20231018\RpcView64.7z to C:\Tools\RpcView...
C:\Tools\RpcView
Added C:\ProgramData\chocolatey\bin\RpcView.exe shim pointed to 'c:\tools\rpcview\rpcview64\rpcview.exe'.
C:\Tools\RpcView\RpcView64\RpcView.exe
 The upgrade of rpcview.vm was successful.
  Software installed to 'C:\Tools\RpcView'
```

2023-10-23 09:40 UTC, Ana06 reviewed
Thanks for the fix @binjo! There is one comment that needs to be removed.

Could you also squash the commits (in order to maintain a clean commit history? Alternatively, we can merge this PR with `squash and merge`

2023-10-23 09:40 UTC, Ana06 commented on packages/rpcview.vm/tools/chocolateyinstall.ps1
> +# $executableName = 'RpcView.exe'
I think this needs to be removed 👀

2023-10-23 09:49 UTC, binjo commented
Looks I don't have permission to `squash and merge` online.

2023-10-23 13:15 UTC, emtuls requested changes
Missing dependency "Microsoft Visual C++ 2019 Redistributable" which is required for tool to work.

2023-10-23 13:15 UTC, emtuls commented on packages/rpcview.vm/rpcview.vm.nuspec
> +    </dependencies>
This package requires "Microsoft Visual C++ 2019 Redistributable" in order to work. Adding this line under `<dependency id="common.vm" />` will make it work:

`<dependency id="vcredist140" version="14.36.32532"/>`

2023-10-25 15:36 UTC, Ana06 requested changes
Thanks for all the work @binjo (and @emtuls for the review)

2023-10-25 15:36 UTC, Ana06 commented on packages/rpcview.vm/rpcview.vm.nuspec
> +      <dependency id="vcredist140" version="14.36.32532"/>
```suggestion
      <dependency id="vcredist140" version="[14.36.32532]" />
```

We should ping the dependency to ensure we test updates or limit it to a lower range like `version="[14.36.32532, 14.37)"`. This dependency is used also in [nmap](https://github.com/mandiant/VM-Packages/blob/a21b189ce92c24c1ca8a85e5d5692fdfccca0cb0/packages/nmap.vm/nmap.vm.nuspec#L12). I think we should create a metapackage to ensure both use the same version and avoid conflicts. I have added this to https://github.com/mandiant/VM-Packages/issues/673 (we can address it in a different PR).

2023-10-27 08:20 UTC, Ana06 approved these changes

2023-10-27 08:26 UTC, binjo approved these changes

2023-10-27 08:27 UTC, merged