Add MemProcFS
mandiant/VM-Packages pull request #776
Opened 2023-12-07 16:13 UTC by naacbin

Add of MemProcFS, a tool to analyze memory images. Also, add a required dependency, dokan, a driver for virtual file system.

Code MemProcFS : https://github.com/ufrisk/MemProcFS
Code Dokan : https://github.com/dokan-dev/dokany

2023-12-08 11:00 UTC, Ana06 reviewed
Could you please squash your commits (avoid `fix linter` commits in order to maintain a clean commit history). Apart from that LGTM.

2023-12-08 11:11 UTC, Ana06 commented on packages/dokan.vm/dokan.vm.nuspec
> +    <version>2.0.6.20231207</version>
[nitpick] fourth segment is not needed

2023-12-22 10:27 UTC, Ana06 requested changes
The tools seem to install & run correctly. Just one minor thing to address regarding the linter.

2023-12-22 10:27 UTC, Ana06 commented on packages/dokan.vm/tools/chocolateyinstall.ps1
> +$category
Please add this package to the linter exclusions instead (the linter should help us writting better code and not making our code uglier 😉 ): https://github.com/mandiant/VM-Packages/blob/main/scripts/test/lint.py#L308

Sorry, I missed it the first time I reviewed it 🙈

2024-01-08 15:57 UTC, naacbin commented
Is there anything left to do on this PR ?

2024-01-08 17:06 UTC, day1player approved these changes

2024-01-10 18:07 UTC, Ana06 approved these changes

2024-01-10 18:07 UTC, merged