Add jadx
mandiant/VM-Packages pull request #780
Opened 2023-12-12 08:30 UTC by naacbin

Add of jadx, a tool to decompile Dalvik bytecode from apk.

Code : https://github.com/skylot/jadx

2023-12-12 11:42 UTC, Ana06 reviewed
Is this tool similar to apktool and Bytecode Viewer? Do we need all the tools?

2023-12-12 11:42 UTC, Ana06 commented on packages/jadx.vm/tools/chocolateyinstall.ps1
> +$category = 'Forensic'
```suggestion
$category = 'Java & Android'
```

2023-12-12 13:13 UTC, naacbin commented
It's not like apktool but seems similar to Bytecode Viewer (both have a GUI).
However, I'm not familiar with Bytecode Viewer and I use jadx a lot. Incorporating this tool into the packages is still important, even if it duplicates functionality with another tool. It's similar to Ghidra/IDA, question of personal preferences.

2023-12-13 06:03 UTC, Ana06 requested changes

2023-12-13 06:03 UTC, Ana06 commented on packages/jadx.vm/tools/chocolateyuninstall.ps1
> +$category = 'Forensic'
```suggestion
$category = 'Java & Android'
```

2023-12-13 06:03 UTC, Ana06 commented
@mandiant/flare-vm opinions on adding this tool to the default FLARE-VM configuration?

2023-12-13 10:58 UTC, mr-tz commented
bytecodeviewer includes jadx so I think this is a duplicate

2023-12-15 17:38 UTC, naacbin commented
Indeed, the decompiler is included in bytecodeviewer. I still prefer the GUI of JADX but bytecodeviewer seems more powerful. I leave it to you to decide whether to close it or not.

2023-12-18 09:50 UTC, Ana06 commented
Thanks for the input @mr-tz! I vote for closing.

2023-12-18 15:41 UTC, closed without merging