Enable openning cmd from context menu
mandiant/VM-Packages pull request #796
Opened 2023-12-18 10:51 UTC by d35ha

Closes https://github.com/mandiant/VM-Packages/issues/786

2023-12-18 15:06 UTC, Ana06 requested changes
Thanks for all the research @d35ha!! 😄

2023-12-19 07:10 UTC, d35ha commented on packages/debloat.vm/tools/win10.xml
> +            <cmd value="Set-ItemProperty -Path Registry::HKEY_CLASSES_ROOT\Directory\shell\flare-ctx-menu-cmd -Name '(Default)' -Value 'Open command window here' -Force -ErrorAction SilentlyContinue"
Done, please review.

2023-12-19 07:27 UTC, d35ha commented
@Ana06  
I noticed that for directories there's an already existing option for opening cmd console with the target directory as the current directory, should I only enable it for directories background (Right click on the directory background)?

![cmd_here](https://github.com/mandiant/VM-Packages/assets/43878201/7ffd7152-349c-40f4-86b0-8be3fcf6a67f)

2023-12-19 09:06 UTC, Ana06 commented
@d35ha 
> I noticed that for directories there's an already existing option for opening cmd console with the target directory as the current directory, should I only enable it for directories background (Right click on the directory background)?

Yes, I think this is a good idea!

What about calling the one for directories background `Cmd here` (instead of `Open command window here`) to keep it consistent with the existent one?

2023-12-19 10:09 UTC, d35ha commented
@Ana06 
> Yes, I think this is a good idea!
> 
> What about calling the one for directories background `Cmd here` (instead of `Open command window here`) to keep it consistent with the existent one?

Done, also removed the icon for consistency.

2023-12-19 10:32 UTC, Ana06 reviewed
@mandiant/commando-vm this PR enables opening cmd from context menu for you as well. I think it is a nice feature also for Commando VM, but mentioning you here in case you have something against it. 😄

2023-12-19 10:32 UTC, Ana06 commented on packages/debloat.vm/tools/win10.xml
> +        <registry-item name="Enable openning cmd from context menu - Default" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd" value="(Default)" type="String" data="Cmd Here" />
Typo
```suggestion
        <registry-item name="Enable opening cmd from context menu - Default" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd" value="(Default)" type="String" data="Cmd Here" />
```

2023-12-19 10:32 UTC, Ana06 commented on packages/debloat.vm/tools/win10.xml
> +        <registry-item name="Enable openning cmd from context menu - Command" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd\command" value="(Default)" type="String" data="cmd.e
Typo
```suggestion
        <registry-item name="Enable opening cmd from context menu - Command" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd\command" value="(Default)" type="String" data="cmd.exe /s /k pushd &quot;%V&quot;" />
```

2023-12-19 10:43 UTC, d35ha commented on packages/debloat.vm/tools/win10.xml
> +        <registry-item name="Enable openning cmd from context menu - Default" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd" value="(Default)" type="String" data="Cmd Here" />
Fixed.

2023-12-19 10:43 UTC, d35ha commented on packages/debloat.vm/tools/win10.xml
> +        <registry-item name="Enable openning cmd from context menu - Command" path="Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\ctx_cmd\command" value="(Default)" type="String" data="cmd.e
Fixed.

2023-12-19 11:18 UTC, Ana06 commented
@d35ha 
> I noticed that for directories there's an already existing option for opening cmd console with the target directory as the current directory, should I only enable it for directories background (Right click on the directory background)?

I wonder what is adding this... I don't have it there in my fresh Windows installation or after a minimal FLARE-VM installation with only few packages. But it is there after I install FLARE-VM with the default configuration. Is a package installing it? which one? 🤔 🕵️ @vm-packages does someone has any idea?

2023-12-19 16:37 UTC, d35ha commented
@Ana06 
It was tricky but got it, the responsible package is the `Malcode Analyst Pack` (map.vm).

![Capture](https://github.com/mandiant/VM-Packages/assets/43878201/badad3c1-0b54-46c3-950d-7e7bbbe66c41)

2023-12-20 09:20 UTC, Ana06 approved these changes
@d35ha 
> It was tricky but got it, the responsible package is the Malcode Analyst Pack (map.vm).

😮 That's great research @d35ha!!!

Then I see two options:
- Leave this PR as it is, as I think it address what is requested in https://github.com/mandiant/VM-Packages/issues/786
- Add also the `Cmd here` option for directories as well using the same registry keys as nmap to ensure that we don't duplicate this entry if the package is installed. This only makes a difference if nmap is not installed.

As we are installing nmap in the default FLARE-VM configuration I tend to think we don't need to make extra changes and we can leave it just as it is. @d35ha what do you think?

2023-12-20 17:46 UTC, d35ha commented
@Ana06 
Honestly, I'm not sure how nmap is related to this problem.
Actually, the `Malcode Analyst Pack` doesn't use registry the same way we're using for registering the context menu options.
It's depending on using a set of COM interfaces upon the triggering of the context menu (that's why it was tricky to trace), it's overcomplicated for us.
I prefer to leave it as it is.

2023-12-20 17:47 UTC, d35ha commented
@Ana06 
Honestly, I'm not sure how nmap is related to this problem.
Actually, the `Malcode Analyst Pack` doesn't use registry the same way we're using for registering the context menu options.
It's depending on using a set of COM interfaces upon the triggering of the context menu (that's why it was tricky to trace), it's overcomplicated for us.
I prefer to leave it as it is.

2023-12-21 11:22 UTC, Ana06 commented
ok, let's merge it then. Thanks for all the research @d35ha!!

2023-12-21 11:22 UTC, merged