Fix VM-Install-Shortcut RunAsAdmin argument
mandiant/VM-Packages pull request #840
Opened 2024-01-17 03:23 UTC by emtuls

This fixes https://github.com/mandiant/VM-Packages/issues/839

2024-01-17 08:28 UTC, mr-tz approved these changes
good catch

2024-01-17 11:27 UTC, Ana06 requested changes
Good catch @emtuls!

I think we should define an arguments variable and add the `RunAsAdmin` if it is `true` instead of duplicating the calls. 🤔

2024-01-17 18:00 UTC, emtuls commented
> Good catch @emtuls!
> 
> I think we should define an arguments variable and add the `RunAsAdmin` if it is `true` instead of duplicating the calls. 🤔

Sounds good! Made the change. 👍

2024-01-17 18:11 UTC, emtuls reviewed
Adjusted as suggested!

2024-01-17 21:59 UTC, emtuls commented on packages/common.vm/tools/vm.common/vm.common.psm1
> +        Install-ChocolateyShortcut $flagsAndArgs
Whoops! I missed testing that case it looks like. I'll fix that!

2024-01-18 16:33 UTC, Ana06 requested changes

2024-01-18 16:33 UTC, Ana06 commented on packages/common.vm/tools/vm.common/vm.common.psm1
> +        $packageArgs = @{
```suggestion
        $shortcutArgs = @{
```

2024-01-18 17:58 UTC, Ana06 approved these changes

2024-01-18 17:59 UTC, merged