Remove Tor Desktop Shortcut
mandiant/VM-Packages pull request #968
Opened 2024-04-01 21:07 UTC by emtuls

This fixes https://github.com/mandiant/VM-Packages/issues/967

2024-04-02 08:58 UTC, Ana06 reviewed
Good catch! I wonder if this is a common enough case and we should make this a helper function.

2024-04-02 08:58 UTC, Ana06 commented on packages/tor-browser.vm/tools/chocolateyinstall.ps1
>    }
what about avoiding code duplication using for loop. Something like:

```suggestion
  # Delete Desktop shortcuts
  ForEach ($location in @(${Env:Public}, ${Env:UserProfile}) {
    $desktopShortcut = Join-Path $location "Desktop\$toolName.lnk"
    if (Test-Path $desktopShortcut) {
      Remove-Item $desktopShortcut -Force -ea 0
    }
```

2024-04-02 18:07 UTC, emtuls commented
It seems useful enough IMO. I do see a few packages we have where it could be useful and it simplifies future desktop shortcut removal from guessing the right way to do it.

2024-04-03 09:20 UTC, Ana06 requested changes
Apart from the version increase, LGTM, thanks!

2024-04-03 09:20 UTC, Ana06 commented on packages/common.vm/common.vm.nuspec
> +    <version>0.0.0.20240402</version>
You need to rebase as the version is the same as in https://github.com/mandiant/VM-Packages/pull/962/files#diff-e403a7afac0855f61eaed356192afac07ee3faf31d423f5e9afd8318ee50c188R5 recently merged

2024-04-09 10:24 UTC, Ana06 approved these changes

2024-04-09 10:24 UTC, merged